import "./globals.css";
import { Inter, Montserrat } from "next/font/google";
import Navbar from "@/components/Navbar";
import { cn } from "@/utils/cn";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          montserrat.className,
          process.env.NEXT_PUBLIC_DEBUG_SCREENS === "true"
            ? "debug-screens"
            : ""
        )}
      >
        <Navbar>{children}</Navbar>
      </body>
    </html>
  );
}
