import type { NextPage } from "next";
import Head from "next/head";

const HomePage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>T2 Next.js Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center items-center h-screen tracking-widest">
        <h1 className="text-2xl font-bold">Let's build. 🚀</h1>
      </main>
    </div>
  );
};

export default HomePage;
